pipeline {
   agent {
       label 'docker'
   }

   options {
       timeout(time: 15, unit: 'MINUTES')
       buildDiscarder(logRotator(numToKeepStr: '2'))
   }

   stages {
      stage('scm') {
         steps {
            git url:'https://github.com/mramanathan/docker_compose_examples', branch: 'master'
         }
      }

      stage('build') {
          steps {
              echo "build docker image, pyappfe"
              dir("with_compose") {
                  sh "sudo docker build --rm --no-cache -t pyappfe:latest -f Dockerfile ."
              }
          }
      }
   }

   post {
       always {
           step([$class: 'WsCleanup'])
       }
   }
}
